### ISSUE TITLE
Introduce support of optimization cache using S3

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#104]
Like in MWoffliner, see https://github.com/openzim/mwoffliner/issues/996 and in Youtube, see https://github.com/openzim/youtube/issues/69

**Comment by rgaudin** [comment]
Thanks @satyamtg for the PR. It's a lot of changes so I figured it would help to define and discuss what needs to be here and let you adjust the PR.

openzim/youtube/issues/69 is a good read.

The most important questions are what we store and how do we store it?

Downloading is not a problem but processing takes a lot of time. We spend **a lot** of time processing xml files at the moment but there's a plan (#110) to change that so let's not consider it for now.

Processing images is what's heavy at the moment so we'll focus on that as images are not supposed to change much (compared to content).

For this we need to define two things: the key to store those images and how do we consider them obsolete.

Given we get our images from URLs, the obvious choice would be to use the source URL as key. There aren't many restrictions to key names [in the doc](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html): UTF-8 1,024bytes long char.

I noticed that mwoffliner chose to not use the URL but `{domain}/{path}`. I guess there's the query part as well but haven't checked.

It might make sense as we have no reason to duplicate URL with different scheme and that makes the occasional browsing of the bucket easier (starts as a virtual folder tree).
We would still need to urlencode it as we don't control the url so:

``` py
url_str = "https://ww2.someplace.state.gov/data/été/some chars/image.jpeg?v=122&from=xxx#yes"
src_url = urllib.parse.urlparse(url_str)
prefix = f"{src_url.scheme}://{src_url.netloc}/"
key = f"{src_url.netloc}/{urllib.parse.quote_plus(src_url.geturl()[len(prefix):])}"
# ww2.someplace.state.gov/data%2F%C3%A9t%C3%A9%2Fsome+chars%2Fimage.jpeg%3Fv%3D122%26from%3Dxxx%23yes
```

that should be more readable but the idea is to get rid of scheme, have a clean root from the domain and then stay safe by urlencoding.

@dattaz @kelson42 @satyamtg let me know what you think. I have no strong opinion in this but once we settle on a format for keys, we'll use same on all scrapers so it's important.

Now since we don't store source files but optimized versions, we need to be able to identify whether a source image has changed or not. 

I think it's important to note that while there is some versioning in S3, we are not using it for reasons I'll not elaborate. So we store only one version of our optimized image and will overwrite it when source file has changed or we want to update it on cache (probably not a scenario we care about). important info here is **one `key` equals one file**, no matter the meta.

What we can do is store the source file ETag as a metadata of our optimized cache file and compare that to the online version when checking for a cached version

``` py
source_etag = requests.head(url=url_str).headers.get("Etag")
if not s3_storage.has_object_matching_meta(key, tag="version", value=source_etag):
    download_from_source()
    optimize()
    s3_storage.upload_file(local_path, key, meta={"version": source_etag})
else:
    s3_storage.download_file(key, local_path)
```

I believe that should help you @satyamtg adjust your PR. I've pushed a commit with requirements fix that you can use.

**Comment by satyamtg** [comment]
@rgaudin thanks for your views on this. I really appreciate it. Coming to the 2 key points that we need to discuss here, I'll address them one by one.
1. **What shall be the key for the objects in the bucket** - In this, I kind of agree with you on the fact that we should make it a bit easy for occasional browsing so start the source domain part. I had also read the manual for Keys [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html). According to this, they have certain characters that we should avoid in the Key which includes characters like '%', '+' etc. (I think the 403 errors that I'm getting while trying to update self destruct time was due to this, but I've got to investigate that). So, what I would suggest for the latter part of the key (after the domain) would be a hash of the entire URL of the source file. We could use MD5 for instance. I don't think it would be much of an overhead to get hashes of URLs. This would ensure that we don't violate any rules. What I'm proposing would look something like this - `{domain}/{Base64 encoded MD5 hash of URL}`


2. **How to identify whether a source file has changed** - To identify a content, we will anyways need to look at the headers using a head request. Etag is actually a good option to check but there's one single problem with it - Not all response headers contain an etag. Take a look at headers for [this](https://lh3.googleusercontent.com/-lLI_l7qCuHY/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rcVrHiczPc6BjfPum5bGYeYDTzNhg/mo/photo.jpg?sz=128) file. It doesn't contain an etag. So, what I would suggest to do is to fallback to content-length (which is a required header) if etag is not found. We then store this (etag or content-length) in the meta and check if meta matches while downloading.


Now talking of my PR, I've actually implemented the logic in the download_image() function itself as that's the controller of all image download tasks in sotoki. Also, I think we should add the image size (width and height) and the format to the key as it would ensure that if 2 or more scrapers download from the same link, they get the correct size and format that they require. However, this would only be helpful if all scrapers use same bucket. @rgaudin @kelson42 @dattaz I would like to know what you think of this.

**Comment by rgaudin** [comment]
>     1. **What shall be the key for the objects in the bucket** According to this, they have certain characters that we should avoid in the Key which includes characters like '%', '+' etc. (I think the 403 errors that I'm getting while trying to update self destruct time was due to this, but I've got to investigate that).

Told you this is a kiwixstorage limitation (didn't account for url as keys) that will be addressed and only concerns wasabi-specific feature (which we don't need here)

> So, what I would suggest for the latter part of the key (after the domain) would be a hash of the entire URL of the source file. We could use MD5 for instance. I don't think it would be much of an overhead to get hashes of URLs. This would ensure that we don't violate any rules. What I'm proposing would look something like this - `{domain}/{Base64 encoded MD5 hash of URL}`

No, this makes it readable only one-way while there is no reason for this. URL encoding is safe ; that's what amazon suggest to use in the doc.

>     2. **How to identify whether a source file has changed** - what I would suggest to do is to fallback to content-length (which is a required header) if etag is not found. We then store this (etag or content-length) in the meta and check if meta matches while downloading.

Agrees we shall have an ETag fallback but that should preferably be `Last-Modified`. `Content-Length` can be false positive but may be acceptable in this case? BTW, none of those headers are **required** per se.

> Now talking of my PR, I've actually implemented the logic in the download_image() function itself as that's the controller of all image download tasks in sotoki. Also, I think we should add the image size (width and height) and the format to the key as it would ensure that if 2 or more scrapers download from the same link, they get the correct size and format that they require. However, this would only be helpful if all scrapers use same bucket. @rgaudin @kelson42 @dattaz I would like to know what you think of this.

I don't really understand this. Sotoki doesn't allow one to choose format or sizes for images right? This cache would be sotoki-specific anyway. We don't share buckets across scrapers as, you've guessed it, we might do completely different things with the same files.

When I said we'll harmonize key namings, that's just for the sake of the python maintainers that we are who are jumping from one scraper to another. There's no actual files shared. Does that make sense?

**Comment by satyamtg** [comment]
@kelson42 I get it. I think what you suggested for the Key previously would be good then. We can do a 3-way fallback then. We would prefer tag, if not found then last-modified, if not found then content-length. (Ah, I get it, I used the wrong word "required". What I meant was that most (if not all) image links have content-length). 

> I don't really understand this. Sotoki doesn't allow one to choose format or sizes for images right? This cache would be sotoki-specific anyway. We don't share buckets across scrapers as, you've guessed it, we might do completely different things with the same files.

I wanted to do it only if we share buckets across scrapers. Since we are not doing it, its not needed. I'll modify my PR to incorporate these changes.

**Comment by kelson42** [comment]
Regarding identifying if a content is outdated in the cache, I don't think there is one approach for all use cases. For example Youtube is trivial and Sotoki images is really not. So probably we need a system which allow to configure the version checking strategy.

Regarding the detail of these strategy, I have nothing much to say. @satyamtg is right, unfortunately, we don't have an etag everywhere. For Sotoki, AFAIK the content is (almost) not mutable, so in a way we could almost assume maybe that we have not check at all to make!? Otherwise size/last-modified approaches sound promising...
