### ISSUE TITLE
More robust image type identification

### ISSUE THREAD

**Issue by satyamtg** [openzim/sotoki#146]
Seeing some zimfarm logs ([this](https://farm.openzim.org/pipeline/5e9f1132793c04047deb7bcb) is a good example job and [this](https://i.imgur.com/xu3OABn.jpg) a good example link), we see that there are a couple of images which have wrong content-type header. Currently we use the header and fall back to magic. This leaves failing resizes and optimizations and may leave traces behind.
```
{"log":"  error: Not a PNG file (libpng failed)\n","stream":"stderr","time":"2020-04-25T06:45:38.902747193Z"}
{"log":"  error: cannot decode image tmpxnuma7egda3ef0ff304fd83af521b7fd919647b0bf09a42b94cd871cbc53bd990c577426.jpg\n","stream":"stderr","time":"2020-04-25T06:45:38.902763553Z"}
```

Should we stop using content-type and rely on magic identification only?

**Comment by rgaudin** [comment]
I am in favor of this. Mentioned it when we changed that I think.
It's supposed to be faster to just rely on the header but since most web servers (apache, nginx) are just mapping file extensions to content-types, it's probably not much better than what we were doing earlier…

So we could either use header and should the optimization fail look into magic and re-optimize or just go straight to magic.

The latter being simpler given the current architecture of the code.

@kelson42 @dattaz ?
