### ISSUE TITLE
Consider using WepP in place of PNG/JPEG/GIF

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#151]
WepP is a next generation image file format which provides better compression ratio than PNG/JPEG/GIF. Therefore this is a good candidate to be put in ZIM files. The support is meanwhile quite good, except for Safari (WIP) and older browsers (user should move on). Because Sotoki ZIM files tend to have a tech savy audience I thought this would be a good candidate to experiment moving our scraper to better file formats. In place of PNG/JPEG/GIF optimisation we would use a converter/optimizer to WebP.

**Comment by satyamtg** [comment]
@kelson42 I think it's a good idea to have WebP in the ZIMs. However, this would have changes on the optimization scheme that we currently have here. I think this gives us a good opportunity to have this incorporated into the scraperlib (like the video module) and then use that here in Sotoki as image optimization is actually being used by many scrapers. What do you think of it?

**Comment by rgaudin** [comment]
While I agree we should move image optimization to the the scraperlib (we've already discussed this), I disagree with several stuff mentioned above.

* Safari support is not WIP. It was there on beta releases and was dropped, most likely due to political reason (Apple chose to support a competitor format, HEIC)
* «User should move on». Wow! A large part of ZIM audience is kiwix-serve and a large part on never-updating scenarios.
* I also disagrees about stack exchange being limited to tech savvy users.
* Chrome had support for it for a long time but Firefox only got it in early 2019.
* WebP is not a success yet. Just like other image formats, it might just never hit and disappears. WP says it's been around for 10y already…
* There's a [JS polyfill](http://webpjs.appspot.com/) but it's another JS hack on the CPU, this time to decode all images… that seems a bit much.
* So far we've only optimized images, keeping them in their original format. This would mean changing the format, so changing the types and the links… that's a heavy change.

The sole benefit is a filesize gain to expect ; but a big one: between 15% and 20% gain from what we currently have.

I think first step should be to convert an existing real-life ZIM with images and test that across readers to validate fallback behavior and quality before we invest too much time into this. I'd advise a small wikipedia with many images (if it's conclusive, this should concern all scrapers).

**Comment by kelson42** [comment]
Should be pretty easy now with https://github.com/openzim/python_scraperlib/issues/26 being implemented.

**Comment by rgaudin** [comment]
One thing that needs a bit of work is how we'd rewrite the HTML to point to `.webp` sources. We could keep the image names as those were but:
- we want to be good-citizen in not advertising wrong formats. We don't like when source website don't respect filenames, so we shouldn't do it ourselves.
- the polyfill relies on the filenames to do its magic.

**Comment by kelson42** [comment]
We need to make a decision on that.

**Comment by rgaudin** [comment]
Implemented ; this is not an option and is applied to both user profile pages and in-post images.

ATM, images are converted to WebP, then resized (128 square for profile, 540 width for in-post) and *optimized*.

WebP polyfill will be added shortly.
