### ISSUE TITLE
Still dead links cases in our ZIM files

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#161]
With the most recent ZIM file generated at https://mirror.download.kiwix.org/zim/stack_exchange/conlang.stackexchange.com_en_all_2020-07.zim

```
$ zimcheck --url_internal conlang.stackexchange.com_en_all_2020-07.zim 
[INFO] Checking zim file conlang.stackexchange.com_en_all_2020-07.zim
[INFO] Verifying Articles' content.. 
[ERROR] Invalid external links found :
  I/question/questions/tagged/diachronics (../../I/question/questions/tagged/diachronics) was not found in article A/question/1042.html
  A/element/59.html (../element/59.html#a59) was not found in article A/question/50.html
  A/user/109.html (../user/109.html) was not found in article A/question/66.html
  A/tag/tolkien-*.html (../tag/tolkien-%2A.html) was not found in article A/question/94.html
[INFO] Overall Test Status: Fail
[INFO] Total time taken by zimcheck: 0 seconds.
```

the 4 errors seems valid so far I was able to check.

**Comment by satyamtg** [comment]
I have looked into it. The links are dead due to the following reasons -
`I/question/questions/tagged/diachronics` - The tag is not resolved properly. The tag is available though in the ZIM
`A/element/59.html` - This page is not available. The question is not at all scraped. Redirect is correct.
`A/user/109.html` - Probably because ZIM did not contain user profiles
`A/tag/tolkien-*.html` - This is something new. The tag is actually redirected to 3 tags, namely, tolkien-elvish, tolkien-black-speech, and tolkein-dwarvish . All 3 are there in the ZIM but this redirection is currently not implemented.

**Comment by satyamtg** [comment]
> `A/element/59.html` - This page is not available. The question is not at all scraped. Redirect is correct.

For this, it's not present on the original online site nor in the dump. Thus we have a successful rewrite but not a redirect to the answer. We currently write redirects while we analyze answers, and since this is not present anymore, we have a dangling link. For fixing this, we would need to somehow know about dangling links

**Comment by rgaudin** [comment]
OK so I guess this is an incorrect link from a user inside a comment, right? In this case, we can skip it for now.
