### ISSUE TITLE
Option to censor forbidden words

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#187]
Based on a list.

**Comment by rgaudin** [comment]
Example list: https://github.com/RobertJGabriel/Google-profanity-words/

**Comment by dattaz** [comment]
Regarding comments on issues #188, maybe this should be implement as python-libzim level, as this is something we may want for all zim content.

**Comment by kelson42** [comment]
I would implement it here first, if this is needed in an other scraper, the consider to move it.

**Comment by rgaudin** [comment]
Implemented via `--censor-words-list` which takes a file or path of one-word-line to censor.

- we replace words and not chars so if we have `anal` (it's in Google's list) in our words list it would remove it in `Here's the anal version` but not in `Here's the analyzed version`. This means that having `sex` in the list doesn't remove `sexy` or `sexual`.
- we replace words in text parts of the document (parsed) and not on the raw markup text. This takes more resources but it's required in order to not break links/urls. We also apply replacements on `<img alt="" title="" />` and `<a title="" />` as those can be set by users.

In any way, this is a very costly option to use but I don't think users without actual need of this would be tempted to use it so it's OK. @Popolechien you should maybe work with the requested so they build-up their list. The shorter the better of course.
