### ISSUE TITLE
Math formulas are not rendered

### ISSUE THREAD

**Issue by mazen-mardini** [openzim/sotoki#283]
Hello!

Math formulas in for example (Theoretical) Computer Science are not rendered. Normally, MathJax should render an expression such as `$a \in R$` to a ∈ _R_, but it doesn't.

I suspect that this affects all StackOverflow packages.

**Comment by kelson42** [comment]
@mazen-mardini Do you have a concrete article in mind?

**Comment by kelson42** [comment]
Indeed, see https://library.kiwix.org/viewer#mathoverflow.net_en_all_2023-01/questions/31448/lower-bounds-in-theoretical-computer-science

**Comment by rgaudin** [comment]
**Original**:
https://mathoverflow.net/questions/227713/estimating-the-size-of-solutions-of-a-diophantine-equation
<img width="745" alt="Screenshot 2023-03-29 at 09 12 44" src="https://user-images.githubusercontent.com/57929/228486154-b43573d8-9aea-46ce-816c-55a02907668c.png">

**ZIM**
https://library.kiwix.org/viewer#mathoverflow.net_en_all_2023-01/questions/227713/estimating-the-size-of-solutions-of-a-diophantine-equation
<img width="730" alt="Screenshot 2023-03-29 at 09 13 16" src="https://user-images.githubusercontent.com/57929/228486308-2a267fe1-88c0-4e08-9ae1-69884e2dcf3a.png">

MathJax is found but not applied 🫤

@kelson42 the questions list doesn't uses mathjax on the original website neither: https://mathoverflow.net/search?q=estimating-the-size-of-solutions-of-a-diophantine-equation

**Comment by mazen-mardini** [comment]
@rgaudin Something else worth noting from your example, is that the embedded image seems to be incorrect as well.

This applies to the earlier version of the question, which the ZIM is based on: https://mathoverflow.net/posts/227713/revisions

**Comment by rgaudin** [comment]
@mazen-mardini thank you for noticing! I've opened a separate ticket.

**Comment by Jaifroid** [comment]
Reddit users are complaining about this here: https://www.reddit.com/r/Kiwix/comments/1g5q59l/how_to_render_latexmathjax_on_kiwix/

**Comment by kelson42** [comment]
New complain here https://github.com/kiwix/kiwix-desktop/issues/1225


 To me, this is priority now to fux this. Too many people are impacted.

**Comment by benoit74** [comment]
It looks like the problem is mostly simple: MathJax configuration is not done properly, so only default MathJax configuration is applied.

Currently, configuring MathJax is based on a `src` attribute (see https://github.com/openzim/sotoki/blob/da6514aa2edee021f5b4fbe8151404910cdd6370/src/sotoki/templates/base.html#L32) where configuration must be inline according to the documentation (https://docs.mathjax.org/en/v2.0-latest/configuration.html).

This means that we do not enable the `$...$` TeX syntax which is disabled by default (https://docs.mathjax.org/en/stable/tex.html).

I hacked the sample webpage on my browser and it works well (all equations are handled by MathJax).

Hacks (not sure all actions are required, I'm too lazy to confirm) are as follow:

Set the configuration inline instead of in an `src` (simply modify the DOM in inspector).

Remove existing MathJax script tag sourcing `../../static/js/MathJax.js?config=TeX-AMS_HTML-full` (simply modify the DOM in inspector).

Cleanup MathJax (in debugger):
```
delete MathJax 
```

Add MathJax back:
```
const newScript = document.createElement('script')
newScript.src = '../../static/js/MathJax.js?config=TeX-AMS_HTML-full' 
document.head.appendChild(script2) 
```

Et voilà.

This now has to be incorporated in the codebase and tested in a real ZIM. 

I'm not that experienced with sotoki, is there a possibility to test a modification without running the full scrape? Or should I just "zimrecreate" the ZIM with one or two modified HTML to confirm the solution? Or I'm maybe just overengineering the thing, it is supposed to take only 1 or 2 hours to run mathoverflow after all.

**Comment by rgaudin** [comment]
Shouldn't be that long. You can push a dev tag to try in ZF if you don't want to invest in this just for this issue which seems like a quick fix
