### ISSUE TITLE
Version 2.1.0 has not been published to pypi

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#302]

**Comment by benoit74** [comment]
Should we publish this manually or tweak the 2.1.0 code base to add necessary CD job?

Since 2.1.1 is underway and will be automatically published to Pypi, I don't think it is necessary to publish 2.1.0 to pypi. No-one used 2.1.0 since it wasn't made available, and it is anyway now significantly broken given changes in SO dump format.

WDYT?

**Comment by kelson42** [comment]
CD should publish packages and binaries

**Comment by benoit74** [comment]
Yes, CD issue is tracked on #303 and most probably fixed on #308 

My question (and this issue) was specifically about 2.1.0, and don't want to invest time in tweaking stuff for useless publishing.

Closing this issue, will reopen if 2.1.1 is still not published to Pypi (but I know this won't be the case)
