### ISSUE TITLE
Latest ZIMs don't work

### ISSUE THREAD

**Issue by okkebal** [openzim/sotoki#66]
I've created some test ZIM's to test the changes I made, all seems fine, but these latest versions that are on download.kiwix.com do not open. I get a white screen, even on subsites that I rendered myself and work fine. 

For example: http://download.kiwix.org/zim/stack_exchange/ai.stackexchange.com_en_all_2017-07.zim  does not open in the Windows version.

**Comment by kelson42** [comment]
I confirm the problem

**Comment by kelson42** [comment]
I should have removed all the problematic files from http://dwonload.kiwix.org/ and currently regenerating the library.xml, etc... I will investigate later was went wrong with this.

**Comment by kelson42** [comment]
The bug seems to have disappear with the last version of the libzim. New stackexchange ZIM files should be OK now. A new run should be done lately end of august. Thank you very much for reporting that problem.

**Comment by okkebal** [comment]
There are still many broken stackexchange zim files on download.kiwix.org. So when is the new run coming?

**Comment by okkebal** [comment]
@kelson42 Please make a run of the StackExchange, Its already end of September, and you said it would run end of august at the latest. 

The current StackExchange files are broken or old layout, if this run works we should have very useful files. 

Pending this issue: https://github.com/kiwix/kiwix-lib/issues/70 it would also work on Android.

**Comment by Popolechien** [comment]
Had additional reports of broken files via OTRS:

http://download.kiwix.org/zim/stack_exchange/android.stackexchange.com_en_all_2017-07.zim
http://download.kiwix.org/zim/stack_exchange/networkengineering.stackexchange.com_en_all_2017-07.zim
http://download.kiwix.org/zim/stack_exchange/programmers.stackexchange.com_en_all_2017-07.zim

"No active ZIM file, please load one first". MD5 hash is good and checks out for the 3 ZIMs but to no avail. Other ZIM the user has are working fine.

**Comment by kelson42** [comment]
Related to https://github.com/openzim/zimwriterfs/issues/18

**Comment by mgautierfr** [comment]
I confirm the issue.

Is it possible to have a "simple" command line to regenerate a zim file ? (`networkengineering.stackexchange.com_en_all_2017-07.zim` is pretty "small", it would be a good candidate for test).

It is pretty difficult to debug zimwriterfs/libzim only with a wrong zim file. Having a reproducer would be great.

**Comment by kelson42** [comment]
@mgautierfr not so far, but I can try to have a look. The whole stuff is done with sotoki (in Python). You could maybe try again by yourself? The README should explain it quite well.

**Comment by kelson42** [comment]
One system has a version of June 27th. I would say the bug has appeard around June, but I can not argue if the bug has not been fixed meanwhile. I think the best now is to try to get a reproduction case.

**Comment by dattaz** [comment]
If you need a very small zim from sotoki use ```esperanto.meta.stackexchange.com``` as argument for [domain of stackechange website]

**Comment by mgautierfr** [comment]
This issue appears when zim file is created using zlib compression (instead of lzma) with a libzim 2.0.0.
There was a bug creating the zlib cluster wrongly (already fixed in libzim 3.0.0 here : https://github.com/openzim/libzim/commit/5aedcd77781aa393af6cfcaf2b5c6eaf7aa62d2f)

This leads to invalid cluster, so invalid zim file.

The new way of reading a zim file in libzim 3.0.0 make libzim crashes badly in this case instead of report an error. (libzim 2.0.0 was a bit more lazy and would have crash or return corrupt data later).

The PR openzim/libzim#64 does different things to solve this:
- Force libzim to compile with lzma support. This way are sure to create zim using lzma compression per default.
- Correctly report error when libzim read a invalid zim file
- (Creation of zim file using zlib compression is already fixed)
