### ISSUE TITLE
Problem by URL rewritting

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#68]
I think I have found a URL rewritting bug.

It concerns last created file:
http://download.kiwix.org/zim/stack_exchange/dsp.stackexchange.com_en_all_2017-10.zim

In the article:
A/question/741/Why-should-I-zero-pad-a-signal-before-taking-the-Fourier-transform.html

The first link points to "previous question" is dead.

**Comment by kelson42** [comment]
@okkebal @dattaz Any idea?

**Comment by okkebal** [comment]
the adress is zim://A/Answer/59.html#a59 this is wrong, because the answers do not have seperate pages in the SE ZIM. It should link to the question page. Which in this case is zim://A/Question/736

In sotoki.py on line 670: 

qans=is_a[0]
a.attrib['href']="../answer/" + qans + ".html#a" + qans

Seems to be the problem. 

It should create a link to to the question page and an anchor to the question, like so:

qans=is_a[0]
qid=link.split("/")[1]
a.attrib['href']= qid + ".html#a" + qans

I don't have time to test this. I hope it works. replace 670 and 671 with above lines.

Line 685 also seems wrong:
a.attrib['href']="../answer/" + qans + ".html#a" + qans

I do not see how to get a question id there to redirect to the corrrect question page. Seems there is none, its a direct link to an answer page... which does not exists. So I guess in this case no link would be better than a broken link? Commenting out line 685 should do the trick

In order to test this I'll have to make a run of dsp.stackexchange.org wich will take about a day on my horrible slow computer :( . 

@dataz  please take a look, maybe I'm wrong here

**Comment by dattaz** [comment]
We have direct link to answers using : answer/[answer_post_id].html#a[answer_post_id] (we build it with redirection file (see [here](https://github.com/openzim/sotoki/blob/master/sotoki/sotoki.py#L227:L228))

Issue here it a wrong extraction of the answer_post_id  : 
Link on the post : https://dsp.stackexchange.com/a/739/59
We have extract "59" has answer_post_id but it should be "739"

I'll take a look closer to resolve this issue (currently generating the zim file)
