### ISSUE TITLE
Add different sort order active/oldest/votes using javascript

### ISSUE THREAD

**Issue by amirouche** [openzim/sotoki#7]

**Comment by kelson42** [comment]
Something we use on youtube scrapper is:
1 - Having everything which might be possible to display on a page in json
2 - filter dyn. with js

This might be use in different scenarios to achieve quick filtering (but this can also be use for the pagination) without any reload.

**Comment by okkebal** [comment]
> Having everything which might be possible to display on a page in json

For Stack Overflow this is going to be very slow if we create one big JSON. Maybe create different JSONS for each tag. It could also be used to search ala Gutenberg. I must say that on my computer Gutenberg runs pretty slow, and on most android browsers (using kiwix-server) it does not work at all. It only works in Firefox.

**Comment by dattaz** [comment]
+1
We will let this open to see if some people(s) come with idea about this feature when we will release zims.

**Comment by kelson42** [comment]
@okkebal thx for your feedback about gutenberg, for me it means we should split things in small chunks/json files.

**Comment by kelson42** [comment]
We need to make a decision on this.

**Comment by amirouche** [comment]
My original idea was to have the choice to order answers depending on activity / score. I think there is two way to go:

- Produce one html per ordering (that will produce a very large zim)
- If answers are not paginated, it is possible to use a javascript script to change the order without the need to rely on JSON because all the required information is already in the page

**Comment by kelson42** [comment]
The online version does not provide such a feature. I don't really see the value myself, like a few other have reported. I believe we should close this ticket as WONTFIX.

**Comment by dattaz** [comment]
The online version provide this feature, you can sort answers to a question by Active/Oldest/Votes.

But I think I misunderstood this ticket until now. I thought it was about sorting the questions (which is a real technical challenge because of the number of questions) and not just having a dynamic display for the answers to a question that are already on a single page (there is no pagination on a question page from memory).

I don't really have an opinion on what to do with the ticket, I don't mind leaving it open until someone takes it. Another possibility is to close it and re-create an explicit one.

**Comment by amirouche** [comment]
Let's close it.

**Comment by kelson42** [comment]
I'm again unsure after the helpful comment of @dattaz. If I understand right now, the goal would be to add the following buttons?
![image](https://user-images.githubusercontent.com/1029718/104309077-deee7680-54d1-11eb-8615-db4523128eaf.png)

I'm not really sure "Active" makes a lot of sense, but would the two other ones be doable in pure javascript (not the buttons, the sorting) based on the DOM infos?

**Comment by rgaudin** [comment]
@kelson42 I think if the issue's opener closed it, we shouldn't bother unless someone else feels strongly about it.

Although it's indeed doable, I don't see much of the value for it: the BY SCORE DESC sorting is the SE's default because it's the most relevant of course. I understand how the *Active* one can be useful, particularly on old questions for which new answers might render old ones obsolete but what's the use case for sorting by Oldest Answers ? I'd say for this scrolling down is enough.

@kelson42 please weight in if you think that's worth doing.

**Comment by kelson42** [comment]
@rgaudin I just guessed that if SO has this, then this is useful.
