### ISSUE TITLE
Automatically detect mathjax (or put it everywhere)

### ISSUE THREAD

**Issue by dattaz** [openzim/sotoki#98]
Follow of #96 
We should automatically detect mathjax domain.
Currently, we have an hardcoded list of domain, which can (should) be update with `sotoki/find_mathml_site.sh` script.

**Comment by kelson42** [comment]
@dattaz Would that be possible to get ride of that web site list and just add it everywhere? I can not figure out how this can impair web site not using it... and like @tigran123 said in comment of #96, potentially alls SE web site use it as this is just a feature offered by the platform.

**Comment by tigran123** [comment]
@kelson42 made a better point than I did --- namely, if stackexchange platform offers such feature as support for MathJax, it would be logically correct to always support it instead of using heuristical hardcoded list which is bound to always be out of date. Please understand that the usage of formulae is not some "feature of the domain of knowledge", but rather an indication of a type of "symbolic" thinking which is applicable everywhere. For some people it is easier to answer questions in words, for others in symbols, which are coded as formulae using LaTeX syntax.

**Comment by tigran123** [comment]
Let me clarify my point by giving an example. Here it is, check it out:

https://philosophy.stackexchange.com/questions/63942/what-is-the-barcan-formula

This is a "philosophy" question, the subject which you judged to be devoid of mathematical formulae --- and, lo and behold, I instantly found the use of formulae therein, as you can see for yourself.

**Comment by tigran123** [comment]
Actually, this may be a more subtle issue, than initially thought. Namely, the "philosophers" seem to be hardcoding primitive Unicode symbols when writing math formulae, instead of using LaTeX, see here:

https://philosophy.stackexchange.com/questions/28312/subformulas-of-the-wff-%e2%88%80x-%e2%88%80y-x-%e2%88%88-y-%e2%88%a8-y-%e2%88%88-x/28317#28317

And when someone attempted to use LaTeX it displayed as raw:

https://philosophy.stackexchange.com/questions/25116/mathematical-logic-question-from-rosen-book

Is this a bug in the stackexchange website which forgot to enable MathJax? Or did the user merely enter the stuff incorrectly? I couldn't see the answer easily by looking at the page source.

**Comment by dattaz** [comment]
I agree with you to get ride of this list. I can't remember why we did not adding on all site, but I remember that there is a reason. I'll take a look at the history to find why.
